# Generated by Django 5.1.7 on 2025-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB', '0002_donor_date_alter_donor_blood_group_alter_donor_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='request',
            name='gender',
        ),
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
