# Generated by Django 5.1.7 on 2025-03-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BB', '0003_remove_donor_gender_remove_request_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='approved',
        ),
    ]
