# Generated by Django 5.1.7 on 2025-05-22 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB', '0004_remove_request_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='pat_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
